from __future__ import annotations

DECISION_APPROVE = "APPROVE"
DECISION_DENY = "DENY"
DECISION_UNCERTAIN = "UNCERTAIN"

REASON_FRAUD = "fraud"
REASON_OCR_FAILURE = "ocr_failure"
REASON_OCR_READ_FAILURE = "ocr_read_failure"

PREDICTABLE_DECISIONS = frozenset({DECISION_APPROVE, DECISION_DENY, DECISION_UNCERTAIN})
